-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.teams
(
    team_id integer,
    product_id integer,
    customer_id integer
);

CREATE TABLE IF NOT EXISTS public.responsibilitiy
(
    responsibilitiy_id integer NOT NULL,
    title character varying(50),
    PRIMARY KEY (responsibilitiy_id)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id integer,
    name character varying(55),
    domain_id integer,
    PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id integer,
    product_description text,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    member_id integer,
    name character varying,
    team_id integer,
    responsibilitiy_id integer,
    PRIMARY KEY (member_id)
);

CREATE TABLE IF NOT EXISTS public.domains
(
    domain_id integer,
    domain_name character varying,
    PRIMARY KEY (domain_id)
);

ALTER TABLE IF EXISTS public.teams
    ADD FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.teams
    ADD FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customers
    ADD FOREIGN KEY (domain_id)
    REFERENCES public.domains (domain_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT responsibilitiy FOREIGN KEY (responsibilitiy_id)
    REFERENCES public.responsibilitiy (responsibilitiy_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (team_id)
    REFERENCES public.teams (team_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;